# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

cubingchina.com	FALSE	/	FALSE	0	CUBINGCHINA_SID	hv0n0dk2a606g8rja2ujd039p1
